### ISSUE TITLE
Remove silent exception catching

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/go-nike-ghr#36]
In a number of places we do:

```
try:
    # nice good code
except:
    pass
```

This will lead to us silently ignoring issues. Just take out the try, the raven/sentry wrapper will catch uncaught exceptions and log them.

**Comment by gitumarkk** [comment]
@imsickofmaps the `try: except` is just a check to see if the Model required field exists i.e. for M&L if there are no previous questions it will return an object DoesNotExists exception, otherwise it will return the query and check whether the quiz should be set to complete, perhaps it will be better to define the specific exception I am trying to catch.

**Comment by imsickofmaps** [comment]
Fixed already
